config/routes.rb
  Rails.application.routes.draw do

  root    "home#index"
  get     "auth/:provider/callback",to: "sessions#create_oauth"
  get     "/users",                 to: "users#index",        as: :users
  get     "/",                      to: "users#new",          as: :signup
  post    "/users",                 to: "users#create"

  get     "/admin",                 to: "users#admin",        as: :admin
  post    "/admin",                 to: "posts#create",       as: :posts
  patch   "/admin/:id",             to: "users#make_admin",   as: :make_admin

  get     "/posts",                 to: "posts#index",        as: :all_posts
  get     "/posts/:id",             to: "posts#show",         as: :post

  get     "/signin",                to: "sessions#new",       as: :signin
  post    "/signin",                to: "sessions#create"
  get     "/my-account",            to: "sessions#show",      as: :my_account
  delete  "/signout",               to: "sessions#destroy",   as: :signout

  get     "/comments/:id",          to: "comments#new",       as: :comment_new
  post    "/comments/:id",          to: "comments#create",    as: :comment_form
  get     "/comment/:id",           to: "comments#show",      as: :comment

  get     "/categories",            to: "categories#index",   as: :categories
  get     "/categories/new",        to: "categories#new",     as: :new_category
  post    "/categories",            to: "categories#create"

  get     "/events",                to: "events#index",       as: :events
  get     "/events/new",            to: "events#new",         as: :new_event
  post    "/events",                to: "events#create"
  get     "/events/:id",            to: "events#show",        as: :event
  get     "/events/:id/edit",       to: "events#edit",        as: :edit_event
  patch   "/events/:id",            to: "events#update"

  get "/calendars",         to: "calendars#index",  as: :calendars
  get "/calendars/:id",     to: "calendars#show",   as: :calendar

  get "/tools",             to: "tools#index",      as: :tools
  post "/tools",            to: "tools#create"
  get "/tools/:id",         to: "tools#show",       as: :tool
  patch "/tools/:id",       to: "tools#update",     as: :edit_tool

  get "/about",             to: "about#index",      as: :about

  require 'resque/server'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :events
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events, :through => :category_events
  has_many :category_events
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  belongs_to :post
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :categories, :through => :category_events
  has_many :category_events
  belongs_to :user

  def self.sort_events_by_date
    @sorted_events = Event.all.sort_by { |event| event.date }.reverse
  end

end

app/models/oauth.rb
class Oauth < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tools
  has_many :comments
  has_many :oauths
  has_many :posts
  has_many :events
  has_secure_password
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_user = User.new

    # for the calendar
    @display_month_year = Date.today.strftime("%B %Y")
    @current_year = Date.today.strftime("%Y").to_i
    @current_month = Date.today.strftime("%m").to_i
    @beginning_of_month = Date.civil(@current_year, @current_month, 1)
    @end_of_month = Date.civil(@current_year, @current_month, -1)

    daily_weather

  end

  def daily_weather
    @api = HTTParty.get("http://api.openweathermap.org/data/2.5/find?q=Seattle&units=imperial")
    @api.parsed_response
    @description = @api["list"][0]["weather"][0]["description"]
    forecast_day
  end

  def forecast_day
    forecast = HTTParty.get("http://api.openweathermap.org/data/2.5/forecast/daily?id=5809844").parsed_response
    @forecast = forecast["list"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # attr_accessor :password

  def index
  end

  def new
    @current_user = User.new
  end

  def create
    @current_user = User.new(user_params)
    if @current_user.save
      session[:user_id] = @current_user.id
      redirect_to root_path, notice: "Thank you, #{@current_user.username}"
    else
      render :new
    end
  end

  def admin
    current_user
    @tool = Tool.new
    @tools = Tool.all
    if @current_user.admin == true
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def make_admin
    if user = User.find(params[:id])
      user.update(admin: true)
      redirect_to my_account_path
    end
  end

  private

  def user_params
    (params.require(:user).permit(:username, :email, :password, :password_confirmation))
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper

  # FOR THE FRONT PAGE CALENDAR
  def find_events_for_current_month
    @events = Event.all.where(date: @beginning_of_month..@end_of_month)
  end

  def get_exact_date(day)
    Date.new(@current_year, @current_month, day)
  end

  def get_events_of_the_day(date)
    @events_of_the_day = Event.all.where(date: date)
  end

  # FOR THE CALENDAR INDEX...repetitive logic for now
  def find_months_to_generate
    @dates_of_each_month = []
    @dates = Event.all.pluck(:date)
    @dates.each do |date|
      @dates_of_each_month << date.beginning_of_month
    end
    @dates_of_each_month.uniq!
  end

  def generate_each_month(month_date)
    @year = month_date.strftime("%Y").to_i
    @month = month_date.strftime("%m").to_i
    @first_of_month = Date.civil(@year, @month, 1)
    @last_of_month = Date.civil(@year, @month, -1)
  end

  def get_date(day)
    Date.new(@year, @month, day)
  end

  def find_events
    @events = Event.all.where(date: @first_of_month..@last_of_month)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def kelvin_to_fahrenheit(k)
    f = 9/5 * (k - 273) + 32

  end

  def cap(weather_description)
    first_letter = weather_description[0].upcase
    rest_of_word = weather_description[1..-1]
    cap_word = rest_of_word.gsub(/\s[a-z]/, &:upcase)
    weather_description = first_letter + cap_word
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper

  def find_user_by_tool(tool_id)
    @user = User.find_by(id: tool_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
<!--  List all user's with their email addresses-->
<!--  Checkbox that turns a user into an admin-->
<!--  A form that lets the admin add new tools-->
<!--  A form that lets the admin add new news posts-->

<h2>Hello <%= @current_user.username %></h2>

<table class="table table-hover">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Make Admin</th>
  </tr>

  <%@users.each do |user| %>
    <tr>
      <% if user != @current_user  %>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
      <% elsif user.admin == nil %>
        <td><%= button_to "Make Admin", make_admin_path(user.id), method: :patch, class:"btn btn-default" %></td>
      <% else %>
        <td><%= user.admin %>
      <%end %>
  <%end %>
  </tr>



</table>


<div class="NewsForm">
  <h4>Make a New Post</h4>

<%= form_for Post.new do |f|  %>
  <%= f.label "title" %>
  <%= f.text_field :title, class:"form-control", placeholder:"Title" %><br>
  <%= f.label "content" %>
  <%= f.text_area :content, class:"form-control", placeholder:"Content" %><br>

  <%= f.submit "Submit", :class => "btn btn-default" %>

<%end %>

<h3>All Tools</h3>
<% @tools.each do |tool| %>
  <%= tool.name %>
<% end %>

<h3>Add Tool</h3>
<%= form_for @tool do |f| %>
  <%= f.label "name" %>
  <%= f.text_field :name %>
  <%= f.hidden_field :user_id, :value => @current_user.id %>
  <%= f.submit "Add tool", :class => "btn btn-default" %>
<% end %>

</div>

app/views/users/new.html.erb
<%= form_for(@current_user, html: { class: "form"}) do |f| %>
  <%= f.label "username:" %><br>
  <%= f.text_field :username %><br>
  <%= f.label "email:" %><br>
  <%= f.text_field :email %><br>
  <%= f.label "password:" %><br>
  <%= f.password_field :password %><br>
  <%= f.label "password confirmation:" %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Create account", :class => "btn btn-default" %>
<% end %>