config/routes.rb
  Rails.application.routes.draw do

  root    "home#index"
  get     "auth/:provider/callback",to: "sessions#create_oauth"
  get     "/users",                 to: "users#index",        as: :users
  get     "/",                      to: "users#new",          as: :signup
  post    "/users",                 to: "users#create"

  get     "/admin",                 to: "users#admin",        as: :admin
  post    "/admin",                 to: "posts#create",       as: :posts
  patch   "/admin/:id",             to: "users#make_admin",   as: :make_admin

  get     "/posts",                 to: "posts#index",        as: :all_posts
  get     "/posts/:id",             to: "posts#show",         as: :post

  get     "/signin",                to: "sessions#new",       as: :signin
  post    "/signin",                to: "sessions#create"
  get     "/my-account",            to: "sessions#show",      as: :my_account
  delete  "/signout",               to: "sessions#destroy",   as: :signout

  get     "/comments/:id",          to: "comments#new",       as: :comment_new
  post    "/comments/:id",          to: "comments#create",    as: :comment_form
  get     "/comment/:id",           to: "comments#show",      as: :comment

  get     "/categories",            to: "categories#index",   as: :categories
  get     "/categories/new",        to: "categories#new",     as: :new_category
  post    "/categories",            to: "categories#create"

  get     "/events",                to: "events#index",       as: :events
  get     "/events/new",            to: "events#new",         as: :new_event
  post    "/events",                to: "events#create"
  get     "/events/:id",            to: "events#show",        as: :event
  get     "/events/:id/edit",       to: "events#edit",        as: :edit_event
  patch   "/events/:id",            to: "events#update"

  get "/calendars",         to: "calendars#index",  as: :calendars
  get "/calendars/:id",     to: "calendars#show",   as: :calendar

  get "/tools",             to: "tools#index",      as: :tools
  post "/tools",            to: "tools#create"
  get "/tools/:id",         to: "tools#show",       as: :tool
  patch "/tools/:id",       to: "tools#update",     as: :edit_tool

  get "/about",             to: "about#index",      as: :about

  require 'resque/server'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :events
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events, :through => :category_events
  has_many :category_events
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  belongs_to :post
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :categories, :through => :category_events
  has_many :category_events
  belongs_to :user

  def self.sort_events_by_date
    @sorted_events = Event.all.sort_by { |event| event.date }.reverse
  end

end

app/models/oauth.rb
class Oauth < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tools
  has_many :comments
  has_many :oauths
  has_many :posts
  has_many :events
  has_secure_password
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_user = User.new

    # for the calendar
    @display_month_year = Date.today.strftime("%B %Y")
    @current_year = Date.today.strftime("%Y").to_i
    @current_month = Date.today.strftime("%m").to_i
    @beginning_of_month = Date.civil(@current_year, @current_month, 1)
    @end_of_month = Date.civil(@current_year, @current_month, -1)

    daily_weather

  end

  def daily_weather
    @api = HTTParty.get("http://api.openweathermap.org/data/2.5/find?q=Seattle&units=imperial")
    @api.parsed_response
    @description = @api["list"][0]["weather"][0]["description"]
    forecast_day
  end

  def forecast_day
    forecast = HTTParty.get("http://api.openweathermap.org/data/2.5/forecast/daily?id=5809844").parsed_response
    @forecast = forecast["list"]
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper

  # FOR THE FRONT PAGE CALENDAR
  def find_events_for_current_month
    @events = Event.all.where(date: @beginning_of_month..@end_of_month)
  end

  def get_exact_date(day)
    Date.new(@current_year, @current_month, day)
  end

  def get_events_of_the_day(date)
    @events_of_the_day = Event.all.where(date: date)
  end

  # FOR THE CALENDAR INDEX...repetitive logic for now
  def find_months_to_generate
    @dates_of_each_month = []
    @dates = Event.all.pluck(:date)
    @dates.each do |date|
      @dates_of_each_month << date.beginning_of_month
    end
    @dates_of_each_month.uniq!
  end

  def generate_each_month(month_date)
    @year = month_date.strftime("%Y").to_i
    @month = month_date.strftime("%m").to_i
    @first_of_month = Date.civil(@year, @month, 1)
    @last_of_month = Date.civil(@year, @month, -1)
  end

  def get_date(day)
    Date.new(@year, @month, day)
  end

  def find_events
    @events = Event.all.where(date: @first_of_month..@last_of_month)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def kelvin_to_fahrenheit(k)
    f = 9/5 * (k - 273) + 32

  end

  def cap(weather_description)
    first_letter = weather_description[0].upcase
    rest_of_word = weather_description[1..-1]
    cap_word = rest_of_word.gsub(/\s[a-z]/, &:upcase)
    weather_description = first_letter + cap_word
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper

  def find_user_by_tool(tool_id)
    @user = User.find_by(id: tool_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="front-wrapper">



<div class="wrap-calendar">


  <% if logged_in? %>
  <div class="center">
    <%= link_to "Add Event", new_event_path, class: "btn btn-info" %>
    <%= link_to "All Calendar Events", calendars_path, class: "btn btn-info" %>
  </div>

  <% else %>
  <div class="center">
    <%= link_to "All Calendar Events", calendars_path, class: "btn btn-info" %>
  </div>
  <% end %>


  <h2 class="calendar-month"><%= @display_month_year %></h2>
  <table id="calendar">
    <tr>
      <th class="day">Sunday</th>
      <th class="day">Monday</th>
      <th class="day">Tuesday</th>
      <th class="day">Wednesday</th>
      <th class="day">Thursday</th>
      <th class="day">Friday</th>
      <th class="day">Saturday</th>
    </tr>

    <tr>

      <% find_events_for_current_month %>

      <% (@beginning_of_month..@end_of_month).each do |d| %>
        <% if d == @beginning_of_month %>
          <% d.wday.times do %> <td class="offset"></td>
        <% end %>
      <% end %>

      <% if d.wday == 0 %>
        </tr><tr>
      <% end %>
        <td class="date-number"><%= d.day %><br>
          <% get_events_of_the_day(get_exact_date(d.day)) %>
          <% @events_of_the_day.each do |event| %>
            <%= link_to event.name, event_path(event) %>
          <% end %></td>
      <% end %>

    </tr>
  </table>
</div>

<div class="wrap-weather">
  <div class="daily-weather">

    <h2><%= @api["list"][0]["name"] %></h2>
    <h4><%= @api.headers["date"]%></h4>
    <h4>
    <%= @api["list"][0]["main"]["temp"].round %>°F<br>
    <%= cap(@description) %><br>
    <%= image_tag "pinkrain.jpg" %><br>
    Humidity: <%= @api["list"][0]["main"]["humidity"] %>%<br>
    Wind: <%= @api["list"][0]["wind"]["speed"].round %> mph<br>
    </h4>
  </div>
</div>

<div class="forecast">
  <% @forecast.each do |day| %>
    <h2><% d = day["dt"]%></h2>
    <h2><%= Time.at(d)  %></h2>
    <h2><%= kelvin_to_fahrenheit(day["temp"]["day"]).round%>°F</h2>
    <h2><%= day["humidity"]%> %</h2>
    <h2><%= cap(day["weather"][0]["description"]) %></h2>
  <% end %>

</div>