config/routes.rb
  Rails.application.routes.draw do

  root    "home#index"
  get     "auth/:provider/callback",to: "sessions#create_oauth"
  get     "/users",                 to: "users#index",        as: :users
  get     "/",                      to: "users#new",          as: :signup
  post    "/users",                 to: "users#create"

  get     "/admin",                 to: "users#admin",        as: :admin
  post    "/admin",                 to: "posts#create",       as: :posts
  patch   "/admin/:id",             to: "users#make_admin",   as: :make_admin

  get     "/posts",                 to: "posts#index",        as: :all_posts
  get     "/posts/:id",             to: "posts#show",         as: :post

  get     "/signin",                to: "sessions#new",       as: :signin
  post    "/signin",                to: "sessions#create"
  get     "/my-account",            to: "sessions#show",      as: :my_account
  delete  "/signout",               to: "sessions#destroy",   as: :signout

  get     "/comments/:id",          to: "comments#new",       as: :comment_new
  post    "/comments/:id",          to: "comments#create",    as: :comment_form
  get     "/comment/:id",           to: "comments#show",      as: :comment

  get     "/categories",            to: "categories#index",   as: :categories
  get     "/categories/new",        to: "categories#new",     as: :new_category
  post    "/categories",            to: "categories#create"

  get     "/events",                to: "events#index",       as: :events
  get     "/events/new",            to: "events#new",         as: :new_event
  post    "/events",                to: "events#create"
  get     "/events/:id",            to: "events#show",        as: :event
  get     "/events/:id/edit",       to: "events#edit",        as: :edit_event
  patch   "/events/:id",            to: "events#update"

  get "/calendars",         to: "calendars#index",  as: :calendars
  get "/calendars/:id",     to: "calendars#show",   as: :calendar

  get "/tools",             to: "tools#index",      as: :tools
  post "/tools",            to: "tools#create"
  get "/tools/:id",         to: "tools#show",       as: :tool
  patch "/tools/:id",       to: "tools#update",     as: :edit_tool

  get "/about",             to: "about#index",      as: :about

  require 'resque/server'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :events
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events, :through => :category_events
  has_many :category_events
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin
  belongs_to :post
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :categories, :through => :category_events
  has_many :category_events
  belongs_to :user

  def self.sort_events_by_date
    @sorted_events = Event.all.sort_by { |event| event.date }.reverse
  end

end

app/models/oauth.rb
class Oauth < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tools
  has_many :comments
  has_many :oauths
  has_many :posts
  has_many :events
  has_secure_password
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper

  # FOR THE FRONT PAGE CALENDAR
  def find_events_for_current_month
    @events = Event.all.where(date: @beginning_of_month..@end_of_month)
  end

  def get_exact_date(day)
    Date.new(@current_year, @current_month, day)
  end

  def get_events_of_the_day(date)
    @events_of_the_day = Event.all.where(date: date)
  end

  # FOR THE CALENDAR INDEX...repetitive logic for now
  def find_months_to_generate
    @dates_of_each_month = []
    @dates = Event.all.pluck(:date)
    @dates.each do |date|
      @dates_of_each_month << date.beginning_of_month
    end
    @dates_of_each_month.uniq!
  end

  def generate_each_month(month_date)
    @year = month_date.strftime("%Y").to_i
    @month = month_date.strftime("%m").to_i
    @first_of_month = Date.civil(@year, @month, 1)
    @last_of_month = Date.civil(@year, @month, -1)
  end

  def get_date(day)
    Date.new(@year, @month, day)
  end

  def find_events
    @events = Event.all.where(date: @first_of_month..@last_of_month)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def kelvin_to_fahrenheit(k)
    f = 9/5 * (k - 273) + 32

  end

  def cap(weather_description)
    first_letter = weather_description[0].upcase
    rest_of_word = weather_description[1..-1]
    cap_word = rest_of_word.gsub(/\s[a-z]/, &:upcase)
    weather_description = first_letter + cap_word
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper

  def find_user_by_tool(tool_id)
    @user = User.find_by(id: tool_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Can you dig it?</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>

  <div class="top-bar">
    <%= link_to "My account", my_account_path(@current_user) %> /
    <%= link_to "Sign Out", signout_path(@current_user), method: :delete %>
  </div>

<% else %>

  <a href="/auth/twitter" class="yellow-link"><%= image_tag "sign-in-with-twitter-gray.png" %></a>

  <div class="col-xs-2 top-right">

    <h2 class="yellow-text">Sign-Up</h2>

    <%= form_for(User.new, html: { class: "form signup-signin" }) do |f| %>
      <%= f.label "username:" %><br>
      <%= f.text_field :username %><br>
      <%= f.label "email address" %><br>
      <%= f.text_field :email %><br>
      <%= f.label "password:" %><br>
      <%= f.password_field :password %><br>
      <%= f.label "password confirmation:" %><br>
      <%= f.password_field :password_confirmation %><br><br>
      <%= f.submit "Create account", :class => "btn btn-default btn-xs" %>
    <% end %>


  </div>

  <div class="col-xs-2 top-right">

    <h2 class="yellow-text-2">Sign-In</h2>

    <%= form_tag "/signin", class: "form signup-signin-2" do %>
      <%= label_tag "username:" %><br>
      <%= text_field_tag :username %><br>
      <%= label_tag "password:" %><br>
      <%= password_field_tag :password %><br><br>
      <%= submit_tag "Sign In", :class => "btn btn-default btn-xs" %>
    <% end %>


  </div>

<% end %>

<div class="whiteout">
  <%= notice %>
  <h1 class="root"><%= link_to "CAN YOU DIG IT?", root_path %></h1>
  <p class="hoe">Here we hoe again!</p>

  <div class="icons-wrapper">
    <div class="icons-n-links">

      <div class="sow col-xs-3">
        <a href="/about"><%= image_tag "sow.gif" %></a><br>
        <%= link_to "SOW WHAT?", "/" %>
      </div>

      <div class="shovel col-xs-3">
        <a href="/tools"><%= image_tag "shovel.gif" %></a><br>
        <%= link_to "TOOLS", tools_path %>
      </div>

      <div class="news col-xs-3">
        <a href="/posts"><%= image_tag "news.gif" %></a><br>
        <%= link_to "NEWS", all_posts_path %>
      </div>

      <div class="events col-xs-3">
        <a href="/calendars"><%= image_tag "party.gif" %></a><br>
        <%= link_to "EVENTS", calendars_path %>
      </div>

    </div>
  </div>




  <%= yield %>
</div>

</body>
</html>